version: '3.8'

services:
  flink-jobmanager:
    image: 'bitnami/flink:latest'
    ports:
      - "6123:6123"
      - "6124:6124"
      - "8081:8081"
    environment:
      - FLINK_MODE=jobmanager
      - |
        FLINK_PROPERTIES=
        jobmanager.bind-host: 0.0.0.0
        jobmanager.blob.server.address: flink-jobmanager
        blob.server.address: flink-jobmanager
        rest.bind-address: flink-jobmanager
        jobmanager.rest.bind-address: flink-jobmanager
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.bind-host: flink-taskmanager

  flink-taskmanager:
    image: 'bitnami/flink:latest'
    ports:
      - "6121:6121"
      - "6122:6122"
    environment:
      - FLINK_MODE=taskmanager
      - |
        FLINK_PROPERTIES=rest.bind-address: flink-taskmanager
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.bind-host: flink-jobmanager
        taskmanager.bind-host: flink-taskmanager
        jobmanager.blob.server.address: flink-jobmanager
    depends_on:
      - flink-jobmanager

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
